context:
  version: 5.2.12

package:
  name: xz
  version: '{{ version }}'

source:
  url: http://downloads.sourceforge.net/project/lzmautils/xz-{{ version }}.tar.bz2
  sha256: fbedff8eb67e229f2e95eb1ff920b255e405c86c9e1a53d4a6861d9823acff18
  patches:
    - 0001-Add-vs2008-support-via-cmake.patch
    - 0002-Add-gettimeofday-for-VS2008.patch

build:
  number: 0
  # run_exports:
    # xz track record of backcompat is very good. Keep default pins (next major version)
    # https://abi-laboratory.pro/tracker/timeline/xz/
    # - '{{ pin_subpackage("xz") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - sel(win and vc<14): c99-to-c89
    - sel(win): cmake
    - sel(win): ninja
    - sel(not win): make
    - sel(not win): automake
    - sel(not win): libtool
  host:
    - sel(win and vc<14): msinttypes

# test:
#   commands:
#     - sel(not win): xz --help
#     - sel(not win): unxz --help
#     - sel(not win): lzma --help
#     - sel(win): xz.exe --help
#     - sel(win): unxz.exe --help
#     - sel(win): if not exist %LIBRARY_PREFIX%\bin\liblzma.dll exit 1
#     - sel(win): if not exist %LIBRARY_PREFIX%\lib\liblzma.lib exit 1
#     - sel(win): if exist %LIBRARY_PREFIX%\lib\liblzma_static.lib exit 1
#     - sel(win): if not exist %LIBRARY_PREFIX%\include\lzma.h exit 1
#     - sel(unix): test -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
#     - sel(unix): test ! -f ${PREFIX}/lib/liblzma.a

features:
  - name: static
    default: false

about:
  home: http://tukaani.org/xz/
  license: LGPL-2.1 and GPL-2.0
  license_file: COPYING
  summary: Data compression software with high compression ratio
  description: |
    XZ Utils is free general-purpose data compression software with a high
    compression ratio. XZ Utils were written for POSIX-like systems, but also
    work on some not-so-POSIX systems.
  doc_url: http://tukaani.org/xz/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  dev_url: http://git.tukaani.org/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - mingwandroid
    - nehaljwani
    - scopatz

