context:
  version: 0.8.1

package:
  name: micromamba
  version: '{{ version }}'

source:
  - url: https://github.com/mamba-org/mamba/archive/{{ version }}.tar.gz
    sha256: abe0a790ef8caf43fb8b5aa18a5a3feaaa9a7e0cb591577952fb10bfebe52e03
  - path: CLI11.hpp
    folder: include/mamba/CLI.hpp

build:
  number: 2
  ignore_run_exports:
    - sel(unix): libcurl
    - sel(unix): libarchive
    - sel(linux): libgcc-ng
    - sel(linux): libstdcxx-ng

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - sel(unix): make
    - sel(win): ninja
  host:
    - cli11
    - cpp-filesystem
    - nlohmann_json
    - bzip2-static
    - zstd-static
    - zlib-static
    - yaml-cpp-static
    - libarchive-static
    - curl-static
    - sel(not win): libssh2-static
    - libsolv-static
    - openssl-static
    - reproc-cpp-static
    - reproc-static

test:
  commands:
    - sel(unix): test -f $PREFIX/bin/micromamba
    - micromamba --help

features:
  - name: static
    default: false

about:
  home: https://github.com/TheSnakePit/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille

