context:
  version: 1.10.0

package:
  name: libssh2
  version: '{{ version }}'

source:
  url: https://www.libssh2.org/download/libssh2-{{ version }}.tar.gz
  sha256: 2d64e90f3ded394b91d3a2e774ca203a4179f69aebee03003e5a6fa621e41d51
  patches:
    - 246c7cb0184b9e1a882c753b412825799c7a9118.patch

build:
  number: 0

requirements:
  build:
    # This breals a dependency cycle:
    # curl->libssh2->cmake->curl
    - sel(win): cmake-binary
    - sel(not win): cmake-no-system
    - sel(not (osx and arm64)): '{{ compiler("c") }}'
    - sel(osx and arm64): '{{ compiler("clang_bootstrap") }}'
    - sel(win): ninja
    - sel(unix): make
  host:
    - openssl-static
    - zlib-static
  run:
    - openssl-static
    - zlib-static

# test:
#   commands:
#     - sel(not win): test -f $PREFIX/include/libssh2.h
#     - sel(not win): test -f $PREFIX/include/libssh2_publickey.h
#     - sel(not win): test -f $PREFIX/include/libssh2_sftp.h

#     # - sel(not win): test ! -f $PREFIX/lib/libssh2.a
#     # - sel(not win): test -f $PREFIX/lib/libssh2${SHLIB_EXT}

#     - sel(win): if not exist %LIBRARY_INC%\\libssh2.h           exit 1
#     - sel(win): if not exist %LIBRARY_INC%\\libssh2_publickey.h exit 1
#     - sel(win): if not exist %LIBRARY_INC%\\libssh2_sftp.h      exit 1
#     # - sel(win): if not exist %LIBRARY_LIB%\\libssh2.lib         exit 1

#     # static testss
#     # - sel(not win): test -f $PREFIX/lib/libssh2.a
#     # - sel(win): if not exist %LIBRARY_LIB%\libssh2_static.lib exit 1

features:
  - name: static
    default: false

about:
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library

  description: |
    libssh2 is a library implementing the SSH2 protocol, available under the revised BSD license.
  dev_url: https://github.com/libssh2/libssh2

extra:
  recipe-maintainers:
    - shadowwalkersb
    - nehaljwani
    - ocefpaf
