context:
  version: 14.2.4

package:
  name: reproc
  version: '{{ version }}'

source:
  - url: https://github.com/DaanDeMeyer/reproc/archive/v{{ version }}.tar.gz
    sha256: 55c780f7faa5c8cabd83ebbb84b68e5e0e09732de70a129f6b3c801e905415dd

build:
  number: 0

test:
  commands:
features:
  - name: static
    default: false

outputs:
  - package:
      name: reproc
    build:
      script:
        - build_c.py
    requirements:
      build:
        - '{{ compiler("c") }}'
        - cmake
        - bitfurnace
        - ninja
  - package:
      name: reproc-cpp
    build:
      script:
        - build_cpp.py
    requirements:
      build:
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
        - cmake
        - bitfurnace
        - ninja
      host:
        - "{{ pin_subpackage('reproc', exact=True ) }}"

about:
  home: https://github.com/DaanDeMeyer/reproc
  license_file: LICENSE
  license: MIT
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies starting, stopping and communicating with external programs.
  dev_url: https://github.com/DaanDeMeyer/reproc

extra:
  recipe-maintainers:
    - wolfv

