context:
  version: 14.2.2

package:
  name: reproc
  version: '{{ version }}'

source:
  - url: https://github.com/DaanDeMeyer/reproc/archive/v{{ version }}.tar.gz
    sha256: 27c88a913bf82ad3b5e4a03f621456d7300a7b77644b1a780c906d26fdd561f5

build:
  number: 0

test:
  commands:
features:
  - name: static
    default: false

outputs:
  - package:
      name: reproc
    build:
      script:
        - sel(unix): build_c.sh
        - sel(win): build_c.bat
    requirements:
      build:
        - '{{ compiler("c") }}'
        - cmake
        - sel(unix): make
        - sel(win): ninja
  - package:
      name: reproc-cpp
    build:
      script:
        - sel(unix): build_cpp.sh
        - sel(win): build_cpp.bat
    requirements:
      build:
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
        - cmake
        - sel(unix): make
        - sel(win): ninja
      host:
        - "{{ pin_subpackage('reproc-static', exact=True ) }}"

about:
  home: https://github.com/DaanDeMeyer/reproc
  license_file: LICENSE
  license: MIT
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies starting, stopping and communicating with external programs.
  dev_url: https://github.com/DaanDeMeyer/reproc

extra:
  recipe-maintainers:
    - wolfv

