context:
  version: 1.0.8

package:
  name: bzip2
  version: '{{ version }}'

source:
  url: https://sourceware.org/pub/bzip2/bzip2-{{ version }}.tar.gz
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
  patches:
    - sel(not win): 0001-cross.patch

build:
  number: 0
  # run_exports:
  # - '{{ pin_subpackage("bzip2") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    # - sel(win): jom
    - sel(win): cmake
    - sel(win): ninja
    - sel(unix): make

features:
  - name: static
    default: false

# test:
#   commands:
#   - sel(unix): bzip2 --help
#   - sel(unix): test -f ${PREFIX}/bin/bunzip2
#   - sel(unix): test -f ${PREFIX}/bin/bzcat
#   - sel(unix): test -f ${PREFIX}/bin/bzcmp
#   - sel(unix): test -f ${PREFIX}/bin/bzdiff
#   - sel(unix): test -f ${PREFIX}/bin/bzegrep
#   - sel(unix): test -f ${PREFIX}/bin/bzfgrep
#   - sel(unix): test -f ${PREFIX}/bin/bzgrep
#   - sel(unix): test -f ${PREFIX}/bin/bzip2recover
#   - sel(unix): test -f ${PREFIX}/bin/bzip2
#   - sel(unix): test -f ${PREFIX}/bin/bzless
#   - sel(unix): test -f ${PREFIX}/bin/bzmore
#   - sel(unix): test -f ${PREFIX}/include/bzlib.h
#   # - sel(unix): test -f ${PREFIX}/lib/libbz2.a
#   # - sel(linux): test -f ${PREFIX}/lib/libbz2.so
#   # - sel(osx): test -f ${PREFIX}/lib/libbz2.dylib
#   - sel(win): if not exist %LIBRARY_INC%\\bzlib.h exit 1
#   - sel(win): if not exist %LIBRARY_LIB%\\bzip2.lib exit 1
#   - sel(win): if not exist %LIBRARY_BIN%\\bzip2.dll exit 1
#   - sel(win): if not exist %LIBRARY_LIB%\\libbz2.lib exit 1
#   - sel(win): if not exist %LIBRARY_BIN%\\libbz2.dll exit 1
#   - sel(win): if not exist %LIBRARY_LIB%\\bzip2_static.lib exit 1
#   - sel(win): if not exist %LIBRARY_LIB%\\libbz2_static.lib exit 1

about:
  home: http://www.bzip.org/
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: |
    Bzip2 is a freely available high-quality data compressor. It typically
    compresses files to within 10% to 15% of the best available techniques,
    whilst being around twice as fast at compression and six times faster
    at decompression.
  doc_url: http://www.bzip.org/docs.html

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - pelson
    - jlanga
    - mingwandroid
    - msarahan

