context:
  name: libev
  version: '4.33'
  sha256: 507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: http://dist.schmorp.de/libev/Attic/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1
  # fix run exports for static libs ...
  # run_exports:
  #   - '{{ pin_subpackage(name, max_pin="x.x") }}'
  skip:
    - win

requirements:
  build:
    - libtool
    - sel(unix): make
    - sel(unix): libtool
    - '{{ compiler("c") }}'

  run_constrained:
    - libevent ==9999999999

features:
  - name: static
    default: false

# test:
#   commands:
#       # Check for headers.
#       - test -f "${PREFIX}/include/ev.h"
#       - test -f "${PREFIX}/include/ev++.h"
#       # TODO
#       # - test ! -f "${PREFIX}/include/event.h"
#       # - test ! -f "${PREFIX}/lib/libev.a"
#       # - sel(unix): test -f "${PREFIX}/lib/libev${SHLIBEXT}"

about:
  home: http://software.schmorp.de/pkg/libev.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A full-featured and high-performance event loop that is loosely modeled after libevent, but without its limitations and bugs.

extra:
  recipe-maintainers:
    - petercable
    - carlodri
    - wolfv
