context:
  version: 3.0.2

package:
  name: openssl
  version: '{{ version }}'

source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: 98e91ccead4d4756ae3c9cde5e09191a8e586d9f4d50838e7ec09d6411dfdb63

build:
  number: 0

features:
  - name: static
    default: false

outputs:
  - package:
      name: openssl

    build:
      no_link:
        - sel(linux): lib/libcrypto.so.1.1
        - sel(osx): lib/libcrypto.1.1.dylib
      # run_exports:
      #   # openssl's versioning is X.Y.Z(rev), where rev is really the patch release ID
      #   #    This pin allows the patch release to be >= the build-time openssl version.
      #   - "{{ pin_subpackage('openssl', max_pin='x.x.x') }}"

    requirements:
      build:
        - '{{ compiler("c") }}'
        - sel(win): nasm
        - sel(unix): make
        - sel(not win): perl
      # Empty host section to ensure that this is identified as cb3
      host:
        # technically a build tool, but the windows makefile really wants to find it in the host env.
        #    easier to do this than carry a patch.
        - sel(win): perl
      run:
        - ca-certificates
    # test:
    #   commands:
    #     - sel(win): copy NUL checksum.txt
    #     - sel(unix): touch checksum.txt
    #     - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
    - carlodri
