context:
  version: 3.0.0

package:
  name: openssl
  version: '{{ version }}'

source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: 59eedfcb46c25214c9bd37ed6078297b4df01d012267fe9e9eee31f61bc70536
  patches:
    # backport from openssl/openssl#16593 to simplify & future-proof build;
    # can be dropped for any version after 3.0.0
    - patches/0001-80-test_cmp_http.t-Fix-handling-of-empty-HTTP-proxy-.patch

build:
  number: 0

features:
  - name: static
    default: false

outputs:
  - package:
      name: openssl

    build:
      no_link:
        - sel(linux): lib/libcrypto.so.1.1
        - sel(osx): lib/libcrypto.1.1.dylib
      # run_exports:
      #   # openssl's versioning is X.Y.Z(rev), where rev is really the patch release ID
      #   #    This pin allows the patch release to be >= the build-time openssl version.
      #   - "{{ pin_subpackage('openssl', max_pin='x.x.x') }}"

    requirements:
      build:
        - '{{ compiler("c") }}'
        - sel(win): nasm
        - sel(unix): make
        - sel(not win): perl
      # Empty host section to ensure that this is identified as cb3
      host:
        # technically a build tool, but the windows makefile really wants to find it in the host env.
        #    easier to do this than carry a patch.
        - sel(win): perl
      run:
        - ca-certificates
    # test:
    #   commands:
    #     - sel(win): copy NUL checksum.txt
    #     - sel(unix): touch checksum.txt
    #     - openssl sha256 checksum.txt

about:
  home: http://www.openssl.org/
  license_file: LICENSE
  license: OpenSSL
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
    - carlodri
