context:
  version: 0.6.3

package:
  name: yaml-cpp
  version: '{{ version }}'

source:
  url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-{{ version }}.tar.gz
  sha256: 77ea1b90b3718aa0c324207cb29418f5bced2354c2e483a9523d98c3460af1ed
  patches:
    - sel(win): pkgconfig.patch

build:
  number: 0
  # run_exports:
  #   - '{{ pin_subpackage("yaml-cpp", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja

# test:
#   files:
#     - test
#   requires:
#     - '{{ compiler("c") }}'
#     - '{{ compiler("cxx") }}'
#     - cmake
#     - ninja
#   commands:
#     - sel(not win): test -f $PREFIX/lib/libyaml-cpp.so
#     - sel(win): if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1

features:
  - name: static
    default: false

about:
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
  doc_url: https://github.com/jbeder/yaml-cpp/wiki/Tutorial
  dev_url: https://github.com/jbeder/yaml-cpp

extra:
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - tadeu
    - seanyen
    - wolfv
