context:
  name: bitfurnace
  version: 0.1.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: file:///Users/wolfvollprecht/Programs/bitfurnace
  git_rev: main


build:
  number: 0
  noarch: true
  script:
    - cp -r bitfurnace $PREFIX

