context:
  name: zstd
  version: 1.4.9

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/facebook/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29ac74e19ea28659017361976240c4b5c5c24db3b89338731a6feb97c038d293
  patches:
    - sel(aarch64): utime-aarch64.patch

build:
  number: 2
  # run_exports:
    # pretty bad removal of symbols in every other micro release:
    #   https://abi-laboratory.pro/tracker/timeline/zstd/
    #  Working smoothly since 1.4.x
    # - '{{ pin_subpackage("zstd", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - sel(win): msinttypes
    - sel(unix): make
    - sel(win): ninja
    - cmake

# test:
#   commands:
#     - zstd -be -i5

#     - sel(unix): test -f ${PREFIX}/include/{{ name }}.h
#     - sel(unix): test ! -f ${PREFIX}/lib/lib{{ name }}.a
#     - sel(linux): test -f ${PREFIX}/lib/lib{{ name }}.so
#     - sel(osx): test -f ${PREFIX}/lib/lib{{ name }}.dylib

#     - sel(win): if not exist %LIBRARY_INC%\{{ name }}.h exit 1
#     - sel(win): if not exist %LIBRARY_BIN%\lib{{ name }}.dll exit 1
#     - sel(win): if not exist %LIBRARY_LIB%\lib{{ name }}.lib exit 1
#     - sel(win): if exist %LIBRARY_LIB%\lib{{ name }}_static.lib exit 1

#     - sel(unix): export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
#     - sel(unix): test -f ${PREFIX}/lib/pkgconfig/lib{{ name }}.pc
#     - sel(unix): pkg-config --cflags lib{{ name }}

features:
  - name: static
    default: false
  - name: programs
    default: false

about:
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
  description: |
    Zstandard is a real-time compression algorithm, providing high compression
    ratios. It offers a very wide range of compression / speed trade-off, while
    being backed by a very fast decoder. It also offers a special mode for
    small data, called dictionary compression, and can create dictionaries from
    any sample set. Zstandard library is provided as open source software using
    a BSD license.
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  dev_url: https://github.com/facebook/zstd

extra:
  recipe-maintainers:
    - rmax
    - msarahan
    - xhochy

