context:
  version: 0.26.0

package:
  name: micromamba
  version: '{{ version }}'

source:
  - url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-{{ version }}.tar.gz
    sha256: 19c1cec502536f5cbec82e2fc56db1c6337fb8b18ddc12472182f9df2e94cc40
  - patches:
      - patches/libmamba_install.patch
      - patches/libmamba_deps.patch

build:
  number: 0
  ignore_run_exports:
    - sel(unix): libcurl
    - sel(unix): libarchive
    - sel(linux): libgcc-ng
    - sel(linux): libstdcxx-ng
    - spdlog

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - sel(unix): make
    - sel(win): ninja
  host:
    - cli11
    - cpp-expected
    - nlohmann_json
    - termcolor-cpp
    - spdlog
    - bzip2-static
    - zstd-static
    - zlib-static
    - yaml-cpp-static
    - libarchive-static
    - curl-static
    - sel(not win): libssh2-static
    - libsolv-static
    - openssl-static
    - reproc-cpp-static
    - reproc-static
    - sel(win): winreg

test:
  commands:
    - sel(unix): test -f $PREFIX/bin/micromamba
    - sel(build_platform == target_platform): micromamba --help

features:
  - name: static
    default: false

about:
  home: https://github.com/TheSnakePit/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - TERMCOLOR_CPP_LICENSE.txt
    - SPDLOG_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille

