context:
  version: '1.16'

package:
  name: libiconv
  version: '{{ version }}'

source:
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-{{ version }}.tar.gz
  sha256: e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
  patches:
    - sel(linux): glibc.patch
    - sel(win): CMakeLists.txt.patch
    - sel(win): config.h.patch
    - sel(win): configure.cmake.patch

build:
  number: 0
  # run_exports:
  #   # Pretty good recently, let's trust them.
  #   #   https://abi-laboratory.pro/tracker/timeline/libiconv/
  #   - '{{ pin_subpackage("libiconv") }}'

requirements:
  build:
    - sel(unix): libtool
    - '{{ compiler("c") }}'
    - sel(win): cmake
    - sel(win): ninja
    - sel(win): m2-patch
    - sel(unix): make

# test:
#   commands:
#     - sel(not win): iconv --help
#     - sel(not win): conda inspect linkages -p $PREFIX $PKG_NAME
#     - sel(osx): conda inspect objects -p $PREFIX $PKG_NAME

features:
  - name: static
    default: false

about:
  home: https://www.gnu.org/software/libiconv/
  license: GPL and LGPL
  license_file: COPYING
  summary: Provides iconv for systems which don't have one (or that cannot convert from/to Unicode.)

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - jhamman
    - scopatz
