context:
  version: "7.87.0"

package:
  name: curl
  version: "{{ version }}"

source:
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
  sha256: 5d6e128761b7110946d1276aff6f0f266f2b726f5e619f7e0a057a474155f307

build:
  number: 0

requirements:
  build:
    - "{{ compiler('c') }}"
    - sel(win): cmake
    - sel(win): ninja
    - sel(unix): make
    - sel(unix): perl
    - sel(unix): pkg-config
    - sel(unix): libtool
  host:
    - sel(linux): openssl-static

features:
  - name: ldap
    default: false
  - name: http2
    description: use libnghttp2 for http2 support
    requirements:
      host:
        - libnghttp2-static
  - name: ssh2
    description: use ssh2 for ssh2 support
    requirements:
      host:
        - libssh2-static
    default: false
  - name: zlib
    description: use zlib for gzip compression support
    requirements:
      host:
        - zlib-static
    default: true
  - name: krb5
    description: use krb5 (gss) for FTP
    requirements:
      host:
        - krb5-static
    default: false
  - name: static
    default: false

about:
  home: http://curl.haxx.se/
  license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

  description: |
    Curl is an open source command line tool and library for transferring data
    with URL syntax. It is used in command lines or scripts to transfer data.
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs

extra:
  recipe-maintainers:
    - msarahan
