context:
  version: "7.72.0"

package:
  name: curl
  version: "{{ version }}"

source:
  url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
  sha256: ad91970864102a59765e20ce16216efc9d6ad381471f7accceceab7d905703ef

build:
  number: 0

requirements:
  build:
    - "{{ compiler('c') }}"
    - make
    - sel(unix): perl
    - sel(unix): pkg-config
  host:
    - openssl-static

features:
  - name: ldap
    default: false
  - name: http2
    description: use libnghttp2 for http2 support
    requirements:
      host:
        - libnghttp2-static
  - name: ssh2
    description: use ssh2 for ssh2 support
    requirements:
      host:
        - libssh2-static
    default: true
  - name: zlib
    description: use zlib for gzip compression support
    requirements:
      host:
        - zlib-static
    default: true
  - name: krb5
    description: use krb5 (gss) for FTP
    requirements:
      host:
        - krb5-static
    default: false
  - name: static
    default: false

about:
  home: http://curl.haxx.se/
  license: MIT/X derivate (http://curl.haxx.se/docs/copyright.html)
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax

  description: |
    Curl is an open source command line tool and library for transferring data
    with URL syntax. It is used in command lines or scripts to transfer data.
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs

extra:
  recipe-maintainers:
    - msarahan
