context:
  version: 3.6.2

package:
  name: libarchive
  version: '{{ version }}'

source:
  url: https://github.com/libarchive/libarchive/archive/v{{ version }}.tar.gz
  sha256: 652b84588488c2ff38db8f666cd7f781163f85bff4449dcb2e16d3c734f96697
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    # This should not be applied in general. It exists so I can build it for
    # debugging Visual Studio where warnings are errors for some reason.
    # Hiding warnings is poor practice.
    # - patches/0005-VC9-compatibility-ignore-some-warnings.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    # These warnings are errors when compiling lz-4 support
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
    # - patches/0008-VC9-compatibility-remove-C99.patch
    # - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch

build:
  number: 0
  # run_exports:
  #   # https://abi-laboratory.pro/index.php?view=timeline&l=libarchive
  #   - '{{ pin_subpackage("libarchive", max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
      # Does not work in this recips at present
      # we manually convert C99 to C89 instead.
      # - c99-to-c89  # [win and vc<14]
    - sel(win and vc<14): msinttypes
    - sel(unix): autoconf
    - sel(unix): automake
    - sel(unix): libtool
    - sel(unix): pkg-config
    - sel(win): cmake
    - sel(unix): make
    - sel(win): ninja
    - sel(win): m2-patch
  host:
    - sel(win and vc<14): msinttypes
    - sel(osx): libiconv-static
  run:
    - sel(osx): libiconv-static

features:
  - name: zlib
    default: true
    requirements:
      host:
        - zlib-static
      run:
        - zlib-static

  - name: zstd
    default: true
    requirements:
      host:
        - zstd-static
      run:
        - zstd-static

  - name: openssl
    default: true
    requirements:
      host:
        - openssl-static
      run:
        - openssl-static

  - name: lzo
    default: true
    requirements:
      host:
        - lzo-static
      run:
        - lzo-static

  - name: xz
    default: true
    requirements:
      host:
        - xz-static
      run:
        - xz-static

  - name: bzip2
    default: true
    requirements:
      host:
        - bzip2-static
      run:
        - bzip2-static

  - name: lz4
    default: true
    requirements:
      host:
        - lz4-c-static
      run:
        - lz4-c-static

  - name: xml2
    default: true
    requirements:
      host:
        - libxml2-static
      run:
        - libxml2-static

  - name: static
    default: false

# test:
#   files:
#   - test/hello_world.xar
#   commands:
#     # Verify pkg-config file is in place.
#   - sel(unix): test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"

#     # Verify headers are in place.
#   - sel(unix): test -f "${PREFIX}/include/archive.h"
#   - sel(unix): test -f "${PREFIX}/include/archive_entry.h"

#   # Verify libraries are in place.
#   # - sel(unix): test -f "${PREFIX}/lib/libarchive.a"
#   # - sel(unix): test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"

#     # Check for commands
#   - bsdcat --version
#   - bsdcpio --version
#   - bsdtar --version
#   - bsdtar -tf test/hello_world.xar

about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD-2-Clause
  license_file: COPYING
  license_family: BSD

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf

