name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Fetch data
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          curl https://github.com/mamba-org/boa-forge/suites/1879702483/artifacts/36686206?access_token=${REPO_TOKEN} -L -o micromamba_pkgs.zip
          unzip micromamba_pkgs.zip -d micromamba_pkgs

          cp ./micromamba_pkgs/win-64/micromamba-0.7.9-h9490d1a_2.tar.bz2 ./micromamba-win.tar.bz2
          cp ./micromamba_pkgs/linux-64/micromamba-0.7.9-hb0f4dca_2.tar.bz2 ./micromamba-linux.tar.bz2
          cp ./micromamba_pkgs/osx-64/micromamba-0.7.9-h0dc7051_2.tar.bz2 ./micromamba-osx.tar.bz2

          tar -xvf micromamba-win.tar.bz2 -C micromamba-win
          tar -xvf micromamba-osx.tar.bz2 -C micromamba-osx
          tar -xvf micromamba-linux.tar.bz2 -C micromamba-linux

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: micromamba_pkgs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-tag-${{ steps.date.outputs.date }}
          release_name: nightly-release-${{ steps.date.outputs.date }}
          body: |
            Test 123.
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload Release Assets Win
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: micromamba-win/Library/bin/micromamba.exe
          asset_name: micromamba.exe
          # asset_content_type: application/exe
      - name: Upload Release Assets Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: micromamba-linux/bin/micromamba
          asset_name: micromamba-linux-64
          # asset_content_type: application/exe
      - name: Upload Release Assets OSX
        id: upload-release-asset-osx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: micromamba-osx/bin/micromamba
          asset_name: micromamba-osx-64
          # asset_content_type: application/exe
