name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
      - uses: actions/download-artifact@v2
        with:
          name: micromamba_pkgs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-tag-${{ steps.date.outputs.date }}
          release_name: nightly-release-${{ steps.date.outputs.date }}
          body: |
            Test 123.
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
